### ISSUE TITLE
Hash Sum mismatch fetching apt packages

### ISSUE THREAD

**Issue by spuder** [rancher/rodeo#12]
Running vagrant up, I get this error:

```
E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/main/source/Sources.xz  Hash Sum mismatch
E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/universe/source/Sources.xz  404  Not Found [IP: 91.189.88.149 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
```
Full error output
```
    node-01:  apt-key add -
    node-01: OK
    node-01: + sh -c add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
    node-01: + [ ubuntu = debian ]
    node-01: + sh -c apt-get update
    node-01: Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
    node-01: Hit:2 http://security.ubuntu.com/ubuntu xenial-security InRelease
    node-01: Get:3 https://download.docker.com/linux/ubuntu xenial InRelease [66.2 kB]
    node-01: Ign:4 http://security.ubuntu.com/ubuntu xenial-security/main Sources
    node-01: Get:5 http://security.ubuntu.com/ubuntu xenial-security/restricted Sources [2116 B]
    node-01: Hit:6 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
    node-01: Get:7 https://download.docker.com/linux/ubuntu xenial/stable amd64 Packages [10.7 kB]
    node-01: Ign:8 http://security.ubuntu.com/ubuntu xenial-security/universe Sources
    node-01: Hit:9 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
    node-01: Get:10 http://archive.ubuntu.com/ubuntu xenial/main Sources [868 kB]
    node-01: Get:11 http://security.ubuntu.com/ubuntu xenial-security/multiverse Sources [3416 B]
    node-01: Get:4 http://security.ubuntu.com/ubuntu xenial-security/main Sources [153 kB]
    node-01: Err:4 http://security.ubuntu.com/ubuntu xenial-security/main Sources
    node-01:   Hash Sum mismatch
    node-01: Get:8 http://security.ubuntu.com/ubuntu xenial-security/universe Sources [111 kB]
    node-01: Err:8 http://security.ubuntu.com/ubuntu xenial-security/universe Sources
    node-01:
    node-01: Get:12 http://archive.ubuntu.com/ubuntu xenial/restricted Sources [4808 B]
    node-01: Get:13 http://archive.ubuntu.com/ubuntu xenial/universe Sources [7728 kB]
    node-01: Get:14 http://archive.ubuntu.com/ubuntu xenial/multiverse Sources [179 kB]
    node-01: Get:15 http://archive.ubuntu.com/ubuntu xenial-updates/main Sources [339 kB]
    node-01: Get:16 http://archive.ubuntu.com/ubuntu xenial-updates/restricted Sources [2536 B]
    node-01: Get:17 http://archive.ubuntu.com/ubuntu xenial-updates/universe Sources [260 kB]
    node-01: Get:18 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse Sources [8764 B]
    node-01: Get:19 http://archive.ubuntu.com/ubuntu xenial-backports/main Sources [4848 B]
    node-01: Get:20 http://archive.ubuntu.com/ubuntu xenial-backports/universe Sources [7120 B]
    node-01: Fetched 9749 kB in 1min 12s (135 kB/s)
    node-01: Reading package lists...
    node-01: E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/main/source/Sources.xz  Hash Sum mismatch
    node-01: E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/universe/source/Sources.xz
    node-01: E: Some index files failed to download. They have been ignored, or old ones used instead.
    node-01: + usermod -aG docker vagrant
    node-01: usermod: group 'docker' does not exist
    node-01: + set -e
    node-01: + [[ -z true ]]
    node-01: + [[ true == \t\r\u\e ]]
    node-01: + exit 0
```
